Fetching Robots.txt File on 301 Redirect
lunchcat/sif pull request #25
Opened 2024-06-14 14:15 UTC by macdoos

<img width="687" alt="Screenshot 2024-06-14 at 16 10 09" src="https://github.com/lunchcat/sif/assets/127897805/3f7dc361-143b-4847-9c11-494ee0379163">

2024-06-14 19:01 UTC, vmfunc commented
Hello, thanks for your pull request! However, anything related to robots.txt are to be done in [pkg/scan/scan.go](https://github.com/lunchcat/sif/blob/main/pkg/scan/scan.go)

2024-06-14 19:02 UTC, vmfunc requested changes

2024-06-14 19:02 UTC, vmfunc commented on sif.go
> +
see https://github.com/lunchcat/sif/blob/main/pkg/scan/scan.go

2024-06-14 19:02 UTC, vmfunc commented on sif.go
> +			}
see https://github.com/lunchcat/sif/blob/main/pkg/scan/scan.go

2024-06-15 20:25 UTC, macdoos commented
@vmfunc reverted changes to main and modified `scan.go`

2024-06-15 20:44 UTC, vmfunc requested changes

2024-06-15 20:44 UTC, vmfunc commented on pkg/scan/scan.go
> +		}
please look into the way we handle logging. do not return an error and use our log package

2024-06-19 02:20 UTC, merged